sudo: false
language: c
os:
  - linux
  - osx
dist: trusty
before_script:
  # - git clone -b nimbus https://github.com/status-im/Nim.git
  - git clone https://github.com/nim-lang/Nim.git
  - cd Nim
  - git clone --depth 1 https://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - ./koch nimble
  - export PATH=$(pwd)/bin:$PATH
  - cd ..
script:
  - nimble install -y
  - nimble tests
